site_name: DataConstructors
copyright: © 2024 DataConstructors. All rights reserved.
repo_url: https://github.com/dataconstructors.github.io
edit_uri: edit/main/docs/


nav:
  - Home: index.md
  - Team: team.md
  - Contact: contact.md

plugins:
- search
- git-revision-date
- macros

theme:
  name: terminal
  pallete: dark
  custom_dir: overrides
  features:
    - footer.prev_next
    - navigation.side.indexes
    - revision.date
    - revision.history