site_name: DataConstructors
copyright: © 2024 DataConstructors. All rights reserved.
repo_url: https://github.com/dataconstructors.github.io
edit_uri: edit/main/docs/
nav:
  - langs:
      es: "/es"
      en: "/#"
  - Home: index.md
  - Team: team.md
  - Contact: contact.md
  - Projects: projects/index.md
plugins:
  - search
  - git-revision-date
  - macros
  - i18n:
      default_language: en
      docs_structure: suffix
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: español
          build: true
theme:
  name: terminal
  pallete: dark
  custom_dir: overrides
  features:
    - footer.prev_next
    - navigation.side.indexes
    - revision.date
    - revision.history
